services:
  graphdb:
    hostname: graphdb
    image: ontotext/graphdb:10.8.4
    ports: 
    - 7200:7200
    - 7300:7300
    volumes:
      - was-graphdb:/opt/graphdb/home

  mockserver:
    image: mockserver/mockserver
    container_name: mockserver
    ports:
      - "1080:1080"
    environment:
      - MOCKSERVER_INITIALIZATION_JSON_PATH=/tmp/mockserver/tractors.json
    volumes:
      - ./mockserver/tractors.json:/tmp/mockserver/tractors.json
    restart: unless-stopped

volumes:
  was-graphdb:
